name: sams_vae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata
  - jupyter
  - leidenalg
  - numpy
  - pandas
  - pyarrow
  - pyro-ppl
  - pytest
  - python=3.9.*
  - pytorch
  - pytorch-cuda=11.7
  - pytorch-lightning
  - redun
  - scanpy
  - scipy
  - scikit-learn
  - seaborn
  - wandb
